# Generated by Django 3.0.1 on 2019-12-29 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20191225_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='tag_line',
            new_name='tagline',
        ),
    ]
